"""Golden tests comparing Python RSP pipeline against GNU Octave (MATLAB) reference outputs.

These tests validate that the Python port produces results consistent with the
original MATLAB implementation by Corman & Crane, run through GNU Octave 10.3.0.

The Octave reference data was generated by run_octave_validation.m using these configs:
  - pig:         curvature cross field, alignment energy, boundary=true, hardedge=false
  - B36:         smooth cross field, distortion energy, boundary=true, hardedge=true
  - SquareMyles: trivial connection, chebyshev energy, boundary=true, hardedge=false

Key differences between Python and Octave outputs:
  - Cross fields from eigensolver (smooth/curvature) may differ due to eigenvector sign
    ambiguity, but produce equivalent parameterizations (same singularity structure,
    same convergence, zero flipped triangles).
  - Trivial connection is deterministic, so SquareMyles should produce closer results.
  - Cut mesh topology can differ (different seam placement), so Xp vertex counts and
    exact UV coordinates may not match. We validate structural properties instead.
"""

import numpy as np
import pytest
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

from rectangular_surface_parameterization.io.read_obj import readOBJ
from rectangular_surface_parameterization.core.mesh_info import mesh_info
from rectangular_surface_parameterization.preprocessing.dec import dec_tri
from rectangular_surface_parameterization.preprocessing.preprocess import preprocess_ortho_param
from rectangular_surface_parameterization.cross_field.face_field import compute_face_cross_field
from rectangular_surface_parameterization.cross_field.curvature_field import compute_curvature_cross_field
from rectangular_surface_parameterization.cross_field.trivial_connection import trivial_connection
from rectangular_surface_parameterization.optimization.reduce_corner_var import reduce_corner_var_2d
from rectangular_surface_parameterization.optimization.reduce_corner_var_cut import reduce_corner_var_2d_cut
from rectangular_surface_parameterization.optimization.reduction import reduction_from_ff2d
from rectangular_surface_parameterization.optimization.solver import optimize_RSP
from rectangular_surface_parameterization.parameterization.integrate import parametrization_from_scales
from rectangular_surface_parameterization.parameterization.seamless import mesh_to_disk_seamless
from rectangular_surface_parameterization.utils.extract_scale import extract_scale_from_param

MESH_DIR = Path(__file__).parent.parent / "Mesh"


@dataclass
class EnergyWeight:
    w_conf_ar: float = 0.0
    w_gradv: float = 1e-2
    w_ang: Optional[float] = None
    w_ratio: Optional[float] = None
    aspect_ratio: Optional[np.ndarray] = None
    ang_dir: Optional[np.ndarray] = None


def load_and_rescale(mesh_name):
    """Load mesh and rescale to unit area (matching MATLAB pipeline)."""
    X, T = readOBJ(str(MESH_DIR / f"{mesh_name}.obj"))[:2]
    cross_prod = np.cross(X[T[:, 0]] - X[T[:, 1]], X[T[:, 0]] - X[T[:, 2]])
    area_tot = np.sum(np.sqrt(np.sum(cross_prod ** 2, axis=1))) / 2
    X = X / np.sqrt(area_tot)
    return mesh_info(X, T)


# Octave reference values (from run_octave_validation.m, GNU Octave 10.3.0)
OCTAVE_GOLDEN = {
    "pig": {
        "config": "curvature/alignment/boundary=true/hardedge=false",
        "num_vertices": 1843,
        "num_faces": 3560,
        "num_edges": 5408,
        "sing_pos": 10,
        "sing_neg": 30,
        "flipped": 0,
        "iterations": 8,
    },
    "B36": {
        "config": "smooth/distortion/boundary=true/hardedge=true",
        "num_vertices": 2280,
        "num_faces": 4556,
        "num_edges": 6834,
        "sing_pos": 32,
        "sing_neg": 24,
        "flipped": 0,
        "iterations": 8,
    },
    "SquareMyles": {
        "config": "trivial/chebyshev/boundary=true/hardedge=false",
        "num_vertices": 706,
        "num_faces": 1328,
        "num_edges": 2034,
        "sing_pos": 4,
        "sing_neg": 4,
        "flipped": 0,
        "iterations": 6,
    },
}


class TestPigCurvatureAlignment:
    """Pig mesh with curvature cross field and alignment energy.

    Octave reference: 0 flipped, 8 iterations, 10+/30- singularities.
    Cross field uses eigensolver so exact values may differ, but singularity
    structure and convergence properties should match.
    """

    @pytest.fixture(scope="class")
    def pipeline_result(self):
        Src = load_and_rescale("pig")
        dec = dec_tri(Src)
        param, Src, dec = preprocess_ortho_param(Src, dec, True, False, 40)

        omega, ang, sing, kappa, Curv = compute_curvature_cross_field(
            Src, param, dec, 30, 1e-1
        )
        aspect_ratio = (np.abs(kappa[:, 0]) + 1e-5) / (np.abs(kappa[:, 1]) + 1e-5)
        t = np.exp(5)
        aspect_ratio = np.clip(aspect_ratio, 1 / t, t)

        weight = EnergyWeight(
            w_gradv=1e-2, w_ang=1, w_ratio=1,
            aspect_ratio=aspect_ratio, ang_dir=ang
        )

        if len(param.ide_bound) > 0:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d_cut(Src, param.ide_bound)
        else:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d(Src)
        k21, Reduction = reduction_from_ff2d(Src, param, ang, omega, Edge_jump, v2t)

        u = np.zeros(Src.num_vertices)
        v = np.zeros(Src.num_vertices)
        result = optimize_RSP(
            omega, ang, u, v, Src, param, dec, Reduction,
            "alignment", weight, False, 200
        )

        disk_mesh, dec_cut, Align, Rot = mesh_to_disk_seamless(
            Src, param, result.angn, sing, k21, True, True, False
        )
        Xp, dX = parametrization_from_scales(
            Src, disk_mesh, dec_cut, param, result.angn, result.om,
            result.ut, result.vt, Align, Rot
        )
        disto = extract_scale_from_param(
            Xp, Src.vertices, Src.triangles, param,
            disk_mesh.triangles, result.angn
        )[0]

        return {
            "Src": Src, "sing": sing, "result": result,
            "Xp": Xp, "disto": disto, "param": param,
        }

    def test_mesh_dimensions(self, pipeline_result):
        Src = pipeline_result["Src"]
        golden = OCTAVE_GOLDEN["pig"]
        assert Src.num_vertices == golden["num_vertices"]
        assert Src.num_faces == golden["num_faces"]
        assert Src.num_edges == golden["num_edges"]

    def test_singularity_counts(self, pipeline_result):
        sing = pipeline_result["sing"]
        golden = OCTAVE_GOLDEN["pig"]
        assert int(np.sum(sing > 1 / 8)) == golden["sing_pos"]
        assert int(np.sum(sing < -1 / 8)) == golden["sing_neg"]

    def test_zero_flipped_triangles(self, pipeline_result):
        disto = pipeline_result["disto"]
        assert np.sum(disto.detJ <= 0) == OCTAVE_GOLDEN["pig"]["flipped"]

    def test_convergence(self, pipeline_result):
        assert pipeline_result["result"].flag == 0

    def test_uv_range_reasonable(self, pipeline_result):
        """UV coordinates should span a reasonable range (not collapsed or exploded)."""
        Xp = pipeline_result["Xp"]
        u_range = Xp[:, 0].max() - Xp[:, 0].min()
        v_range = Xp[:, 1].max() - Xp[:, 1].min()
        assert 0.1 < u_range < 10.0
        assert 0.1 < v_range < 10.0


class TestB36SmoothDistortion:
    """B36 mesh with smooth cross field, hard edges, and distortion energy.

    Octave reference: 0 flipped, 8 iterations, 32+/24- singularities.
    """

    @pytest.fixture(scope="class")
    def pipeline_result(self):
        Src = load_and_rescale("B36")
        dec = dec_tri(Src)
        param, Src, dec = preprocess_ortho_param(Src, dec, True, True, 40)

        omega, ang, sing = compute_face_cross_field(Src, param, dec, 10)

        weight = EnergyWeight(w_conf_ar=0.5, w_gradv=1e-2)

        if len(param.ide_bound) > 0:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d_cut(Src, param.ide_bound)
        else:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d(Src)
        k21, Reduction = reduction_from_ff2d(Src, param, ang, omega, Edge_jump, v2t)

        u = np.zeros(Src.num_vertices)
        v = np.zeros(Src.num_vertices)
        result = optimize_RSP(
            omega, ang, u, v, Src, param, dec, Reduction,
            "distortion", weight, False, 200
        )

        disk_mesh, dec_cut, Align, Rot = mesh_to_disk_seamless(
            Src, param, result.angn, sing, k21, True, True, True
        )
        Xp, dX = parametrization_from_scales(
            Src, disk_mesh, dec_cut, param, result.angn, result.om,
            result.ut, result.vt, Align, Rot
        )
        disto = extract_scale_from_param(
            Xp, Src.vertices, Src.triangles, param,
            disk_mesh.triangles, result.angn
        )[0]

        return {
            "Src": Src, "sing": sing, "result": result,
            "Xp": Xp, "disto": disto,
        }

    def test_mesh_dimensions(self, pipeline_result):
        Src = pipeline_result["Src"]
        golden = OCTAVE_GOLDEN["B36"]
        assert Src.num_vertices == golden["num_vertices"]
        assert Src.num_faces == golden["num_faces"]
        assert Src.num_edges == golden["num_edges"]

    def test_singularity_counts(self, pipeline_result):
        sing = pipeline_result["sing"]
        golden = OCTAVE_GOLDEN["B36"]
        assert int(np.sum(sing > 1 / 8)) == golden["sing_pos"]
        assert int(np.sum(sing < -1 / 8)) == golden["sing_neg"]

    def test_zero_flipped_triangles(self, pipeline_result):
        disto = pipeline_result["disto"]
        assert np.sum(disto.detJ <= 0) == OCTAVE_GOLDEN["B36"]["flipped"]

    def test_convergence(self, pipeline_result):
        assert pipeline_result["result"].flag == 0

    def test_uv_range_reasonable(self, pipeline_result):
        Xp = pipeline_result["Xp"]
        u_range = Xp[:, 0].max() - Xp[:, 0].min()
        v_range = Xp[:, 1].max() - Xp[:, 1].min()
        assert 0.1 < u_range < 10.0
        assert 0.1 < v_range < 10.0


class TestSquareMylesTrivialChebyshev:
    """SquareMyles mesh with trivial connection and chebyshev energy.

    Octave reference: 0 flipped, 6 iterations, 4+/4- singularities.
    Trivial connection is deterministic (no eigensolver), so results should
    be structurally identical.
    """

    @pytest.fixture(scope="class")
    def pipeline_result(self):
        Src = load_and_rescale("SquareMyles")
        dec = dec_tri(Src)
        param, Src, dec = preprocess_ortho_param(Src, dec, True, False, 40)

        sing = np.zeros(Src.num_vertices)
        sing[param.idx_bound] = np.round(
            4 * param.Kt[param.idx_bound] / (2 * np.pi)
        ) / 4
        omega, ang, sing = trivial_connection(Src, param, dec, True, False, sing)

        weight = EnergyWeight(w_gradv=1e-2)

        if len(param.ide_bound) > 0:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d_cut(Src, param.ide_bound)
        else:
            Edge_jump, v2t, base_tri = reduce_corner_var_2d(Src)
        k21, Reduction = reduction_from_ff2d(Src, param, ang, omega, Edge_jump, v2t)

        u = np.zeros(Src.num_vertices)
        v = np.zeros(Src.num_vertices)
        result = optimize_RSP(
            omega, ang, u, v, Src, param, dec, Reduction,
            "chebyshev", weight, False, 200
        )

        disk_mesh, dec_cut, Align, Rot = mesh_to_disk_seamless(
            Src, param, result.angn, sing, k21, True, True, False
        )
        Xp, dX = parametrization_from_scales(
            Src, disk_mesh, dec_cut, param, result.angn, result.om,
            result.ut, result.vt, Align, Rot
        )
        disto = extract_scale_from_param(
            Xp, Src.vertices, Src.triangles, param,
            disk_mesh.triangles, result.angn
        )[0]

        return {
            "Src": Src, "sing": sing, "result": result,
            "Xp": Xp, "disto": disto,
        }

    def test_mesh_dimensions(self, pipeline_result):
        Src = pipeline_result["Src"]
        golden = OCTAVE_GOLDEN["SquareMyles"]
        assert Src.num_vertices == golden["num_vertices"]
        assert Src.num_faces == golden["num_faces"]
        assert Src.num_edges == golden["num_edges"]

    def test_singularity_counts(self, pipeline_result):
        sing = pipeline_result["sing"]
        golden = OCTAVE_GOLDEN["SquareMyles"]
        assert int(np.sum(sing > 1 / 8)) == golden["sing_pos"]
        assert int(np.sum(sing < -1 / 8)) == golden["sing_neg"]

    def test_zero_flipped_triangles(self, pipeline_result):
        disto = pipeline_result["disto"]
        assert np.sum(disto.detJ <= 0) == OCTAVE_GOLDEN["SquareMyles"]["flipped"]

    def test_convergence(self, pipeline_result):
        assert pipeline_result["result"].flag == 0

    def test_uv_range_close_to_octave(self, pipeline_result):
        """SquareMyles UV range should be close to Octave reference.

        Octave: [-0.587, 0.587] x [-0.588, 0.588]
        Tolerance is generous because the KKT solver may produce different
        (but valid) solutions.
        """
        Xp = pipeline_result["Xp"]
        u_range = Xp[:, 0].max() - Xp[:, 0].min()
        v_range = Xp[:, 1].max() - Xp[:, 1].min()
        # Octave ranges: ~1.175 x ~1.176
        assert abs(u_range - 1.175) < 0.2
        assert abs(v_range - 1.176) < 0.2
